# Generated by Django 5.1.2 on 2024-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
