# Generated by Django 5.1.2 on 2024-11-16 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='InsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insole_model', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OpenClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_close', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/gallery')),
                ('alt_text', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SoleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sole_material', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_material', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('air_circulation', models.BooleanField(default=False)),
                ('waterproof', models.BooleanField(default=False)),
                ('capsule_in_heel', models.BooleanField(default=False)),
                ('capsule_in_claw', models.BooleanField(default=False)),
                ('main_image', models.ImageField(upload_to='product/main')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ManyToManyField(related_name='product', to='ProductApp.color')),
                ('insole_model', models.ManyToManyField(related_name='product', to='ProductApp.insolemodel')),
                ('open_close', models.ManyToManyField(related_name='product', to='ProductApp.openclose')),
                ('gallery_image', models.ManyToManyField(blank=True, related_name='product', to='ProductApp.productgallery')),
                ('size', models.ManyToManyField(related_name='product', to='ProductApp.size')),
                ('sole_material', models.ManyToManyField(related_name='product', to='ProductApp.solematerial')),
                ('top_material', models.ManyToManyField(related_name='product', to='ProductApp.topmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
