# Generated by Django 5.1.1 on 2024-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insole_model', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SoleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sole_material', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_material', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='product/gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='ProductApp.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='ProductApp.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='insole_model',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='ProductApp.insolemodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='sole_material',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='ProductApp.solematerial'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_material',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='ProductApp.topmaterial'),
        ),
    ]
