# Generated by Django 5.1.2 on 2024-11-17 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_alter_product_name_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=25, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='insolemodel',
            name='insole_model',
            field=models.CharField(max_length=15, verbose_name='جنس داخل'),
        ),
        migrations.AlterField(
            model_name='openclose',
            name='open_close',
            field=models.CharField(max_length=20, verbose_name='نحوه باز و بسته شدن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='air_circulation',
            field=models.BooleanField(default=False, verbose_name='گردش هوا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_in_claw',
            field=models.BooleanField(default=False, verbose_name='کپسول فشار در قسمت پاشنه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_in_heel',
            field=models.BooleanField(default=False, verbose_name='کپسول فشار در قسمت پنجه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product', to='ProductApp.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery_image',
            field=models.ManyToManyField(blank=True, related_name='product', to='ProductApp.productgallery', verbose_name='گالری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insole_model',
            field=models.ManyToManyField(related_name='product', to='ProductApp.insolemodel', verbose_name='جنس داخل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product/main', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_close',
            field=models.ManyToManyField(related_name='product', to='ProductApp.openclose', verbose_name='نحوه باز و بسته شدن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='product', to='ProductApp.size', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sole_material',
            field=models.ManyToManyField(related_name='product', to='ProductApp.solematerial', verbose_name='جنس کفه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_material',
            field=models.ManyToManyField(related_name='product', to='ProductApp.topmaterial', verbose_name='جنس رویه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='waterproof',
            field=models.BooleanField(default=False, verbose_name='ضد اب'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='product/gallery', verbose_name='گالری'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=25, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='solematerial',
            name='sole_material',
            field=models.CharField(max_length=15, verbose_name='جنس کفی'),
        ),
        migrations.AlterField(
            model_name='topmaterial',
            name='top_material',
            field=models.CharField(max_length=15, verbose_name='جنس رویه'),
        ),
    ]
