# Generated by Django 5.1.1 on 2024-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_insolemodel_solematerial_topmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1000000, max_length=9),
        ),
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
