# Generated by Django 5.1.1 on 2024-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_product_discount_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Capsule_in_claw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='air_circulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_in_heel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='waterproof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=1000000, max_length=10),
        ),
    ]
