# Generated by Django 5.1.1 on 2024-09-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_product_capsule_in_claw_product_air_circulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Capsule_in_claw',
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='introduction', to='ProductApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_in_claw',
            field=models.BooleanField(default=False),
        ),
    ]
