# Generated by Django 5.1.1 on 2024-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_remove_product_capsule_in_claw_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
