# Generated by Django 5.1.2 on 2024-11-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0006_alter_product_insole_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
