# Generated by Django 5.1.1 on 2024-10-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0008_rename_text_comment_body_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
