# Generated by Django 5.1.2 on 2024-12-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
        ('ProductApp', '0007_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ProductApp.product'),
        ),
    ]
