# Generated by Django 5.1.2 on 2024-12-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0004_alter_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='code_posti',
            new_name='National_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='meli_code',
            new_name='Postal_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='plak',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='vahed',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='ostan',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
